/**
 * CarScout36
 * A simple RESTful web-service that allows users to place new car adverts and view, modify and delete existing car adverts.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: samy@samyateia.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package model
import play.api.libs.json._
import java.util.Date
import java.util.UUID

case class Advert (
                  id: String,
                  title: String,
                  fuel:  Option[AdvertFuelEnum.AdvertFuelEnum],
                  price: Int,
                  `new`: Boolean,
                  mileage: Option[Int],
                  firstRegistration: Option[Date]
)

object Advert {
implicit val format: Format[Advert] = Json.format
}

object AdvertFuelEnum extends Enumeration {
  val   diesel, gasoline = Value
  type AdvertFuelEnum = Value
  implicit val format: Format[Value] = Format(Reads.enumNameReads(this), Writes.enumNameWrites[AdvertFuelEnum.type])
}
